
#####################################################
################     spring核心配置     #############
#####################################################

#系统配置
server:
  port: 8080
#debug: true #不会打印spring的debug和mybatis的debug信息等
#trace: true #基本打印打印所有debug信息和trace级别的信息


spring:
  main:
    #懒加载配置
    #  全局懒加载 基本上会加入spring容器的bean都会懒加载  filter除外
    #  也可以通过main方法调用SpringApplicationBuilder#lazyInitialization  或者SpringApplication#setLazyInitialization
    lazy-initialization: false
  profiles:
    include:
      - mysql
      - redis
      - value
      - log
#    active: mysql,redis,value


#  健康检查配置 Actuator
management:
  endpoint:
    health:
      enabled: true
      show-details: always

