



#####################################################
################     mysql配置     ##################
#####################################################


# value配置
database:
  name: mysql-dev
  version: 5.6.1


