

#####################################################
############             java日志         ###########
#####################################################


#   %n - 换行
#   %m - 日志内容
#   %p - 日志级别(FATAL,   ERROR,   WARN,   INFO,   DEBUG   or   custom)
#   %r - 程序启动到现在的毫秒数
#   %% - percent   sign   in   output
#   %t - 当前线程名
#   %d   -  日期和时间,
#       常用的格式有 %d{DATE}, %d{ABSOLUTE}, %d{HH:mm:ss,SSS}, %d{ddMMyyyy HH:mm:ss,SSS}。。。
#   %l - 同 %F%L%C%M
#   %F - java源文件名
#   %L - java源码行数
#   %C - java类名,%C{1} 输出最后一个元素
#   %M-java方法名

#  加颜色   %clr(内容){颜色名字}   blue cyan faint green magenta red yellow

logging:
  file:
    name: /Java/file/springboot.log
    max-history: 14
    max-size: 100MB #日志文件达到100MB以后 就会自动分包 springboot.log.2020-07-23.数字.gz
  pattern:
    console: '%clr(%d{MM/dd HH:mm:ss.SSS}){magenta} [%t] %clr(%p){red} %clr(%C{0}.%M.java:%L){cyan}: %m %n'
    file: '%d{MM/dd HH:mm:ss.SSS} [%t] %p %C{0}.%M.java:%L: %m %n'
  level:
    web: debug # 可以看到springMVC中的一些初始化 比如加载filter的顺序和过滤规则 Servlet的过滤规则
#    root: info
#    sql: debug
    org:
      hibernate: error
      springframework:
        web: debug
