



#####################################################
################     mysql配置     ##################
#####################################################


# value配置
database:
  name: mysql-pro
  version: 5.6.1

